/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MerchantRole;


import Business.Supplier.Supplier;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Component;
import java.awt.Font;

/**
 *
 * @author zhuchenyan
 */
public class MerchantHP extends javax.swing.JPanel {

    /**
     * Creates new form LogisticsCoordinatorHP
     */
    private Supplier supplier;
    private String username;
    private UserAccount account;
    private JPanel userProcessContainer;
    
    public MerchantHP() {
        initComponents();
        // Set CardLayout for jPanel
        MerchantWorkAreajPanel.setLayout(new CardLayout());
        setupTheme();
    }
    
    // Constructor with username parameter
    public MerchantHP(String username) {
        initComponents();
        this.username = username;
        
        // Set CardLayout for panel
        MerchantWorkAreajPanel.setLayout(new CardLayout());
        setupTheme();
    }
    
    // Constructor with userProcessContainer and username parameters
    public MerchantHP(JPanel userProcessContainer, String username) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.username = username;
        
        // Set CardLayout for panel
        MerchantWorkAreajPanel.setLayout(new CardLayout());
        setupTheme();
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    
    public Supplier getSupplier() {
        return supplier;
    }
    
    public void setAccount(UserAccount account) {
        this.account = account;
    }
    
    public UserAccount getAccount() {
        return account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        MerchantjPanel = new javax.swing.JPanel();
        btnProductCatalog = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnViewMerchantRequest = new javax.swing.JButton();
        btnTracking = new javax.swing.JButton();
        MerchantWorkAreajPanel = new javax.swing.JPanel();

        btnProductCatalog.setText("Manage Product Catalog");
        btnProductCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductCatalogActionPerformed(evt);
            }
        });

        btnReports.setText("Sales Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnProfile.setText("My Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        btnViewMerchantRequest.setText("View Merchant Request");
        btnViewMerchantRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMerchantRequestActionPerformed(evt);
            }
        });

        btnTracking.setText("Tracking Information");
        btnTracking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrackingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MerchantjPanelLayout = new javax.swing.GroupLayout(MerchantjPanel);
        MerchantjPanel.setLayout(MerchantjPanelLayout);
        MerchantjPanelLayout.setHorizontalGroup(
            MerchantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MerchantjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MerchantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnTracking, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewMerchantRequest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MerchantjPanelLayout.createSequentialGroup()
                        .addGroup(MerchantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProductCatalog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnReports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MerchantjPanelLayout.setVerticalGroup(
            MerchantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MerchantjPanelLayout.createSequentialGroup()
                .addGap(271, 271, 271)
                .addComponent(btnProductCatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(btnReports, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnViewMerchantRequest, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnTracking, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2214, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(MerchantjPanel);

        javax.swing.GroupLayout MerchantWorkAreajPanelLayout = new javax.swing.GroupLayout(MerchantWorkAreajPanel);
        MerchantWorkAreajPanel.setLayout(MerchantWorkAreajPanelLayout);
        MerchantWorkAreajPanelLayout.setHorizontalGroup(
            MerchantWorkAreajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1397, Short.MAX_VALUE)
        );
        MerchantWorkAreajPanelLayout.setVerticalGroup(
            MerchantWorkAreajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2888, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(MerchantWorkAreajPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductCatalogActionPerformed
        // Check if supplier is null
        if (supplier == null) {
            // Create a default supplier if not set
            supplier = new Business.Supplier.Supplier();
            supplier.setSupplyName("Default Supplier");
        }
        
        // Create the product catalog panel
        ManageProductCatalogJPanel manageProductCatalogJPanel = new ManageProductCatalogJPanel(MerchantWorkAreajPanel, supplier);
        MerchantWorkAreajPanel.add("ManageProductCatalogJPanel", manageProductCatalogJPanel);
        CardLayout layout = (CardLayout) MerchantWorkAreajPanel.getLayout();
        layout.next(MerchantWorkAreajPanel);    
    }//GEN-LAST:event_btnProductCatalogActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        SalesReport salesReport = new SalesReport(MerchantWorkAreajPanel);
        MerchantWorkAreajPanel.add("SalesReport", salesReport);
        CardLayout layout = (CardLayout) MerchantWorkAreajPanel.getLayout();
        layout.next(MerchantWorkAreajPanel);  
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // Use the class account variable instead of looking it up
        System.out.println("MerchantHP: Profile button clicked, current account: " + 
            (account != null ? account.getUsername() : "null") + ", username: " + username);
            
        if (account == null) {
            System.out.println("MerchantHP: Account is null, trying to find account for username: " + username);
            try {
                // Print all user accounts in the system for debugging
                System.out.println("MerchantHP: Available users in system:");
                for (Business.UserAccount.UserAccount ua : Business.EcoSystem.getInstance().getUserAccountDirectory().getUserAccountList()) {
                    System.out.println(" - Username: " + ua.getUsername());
                }
                
                // Try to find by exact username match
                for (Business.UserAccount.UserAccount ua : Business.EcoSystem.getInstance().getUserAccountDirectory().getUserAccountList()) {
                    if (ua.getUsername() != null && ua.getUsername().equals(this.username)) {
                        account = ua;
                        System.out.println("MerchantHP: Found matching account: " + ua.getUsername());
                        break;
                    }
                }
                
                // If still null but username is "m", try finding merchant account
                if (account == null && "m".equals(this.username)) {
                    System.out.println("MerchantHP: Trying special case for merchant user 'm'");
                    for (Business.UserAccount.UserAccount ua : Business.EcoSystem.getInstance().getUserAccountDirectory().getUserAccountList()) {
                        if ("m".equals(ua.getUsername())) {
                            account = ua;
                            System.out.println("MerchantHP: Found merchant account with username 'm'");
                            break;
                        }
                    }
                }
            } catch (Exception e) {
                System.out.println("MerchantHP: Error searching for account: " + e.getMessage());
                e.printStackTrace();
            }
            
            // If still null after lookup, show error
            if (account == null) {
                System.out.println("MerchantHP: Failed to find account, showing error message");
                javax.swing.JOptionPane.showMessageDialog(this, 
                        "Unable to get user information, please login again.", 
                        "Error", 
                        javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
        }
        
        // Create ManageOwnProfile panel with account data
        System.out.println("MerchantHP: Creating ManageOwnProfile with account: " + account.getUsername());
        ManageOwnProfile manageOwnProfile = new ManageOwnProfile(MerchantWorkAreajPanel, account);
        MerchantWorkAreajPanel.add("ManageOwnProfile", manageOwnProfile);
        CardLayout layout = (CardLayout) MerchantWorkAreajPanel.getLayout();
        layout.next(MerchantWorkAreajPanel);  
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnViewMerchantRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMerchantRequestActionPerformed
        // 创建ViewMerchantRequestsJPanel面板
        ViewMerchantRequestsJPanel viewMerchantRequestsJPanel = new ViewMerchantRequestsJPanel(MerchantWorkAreajPanel);
        MerchantWorkAreajPanel.add("ViewMerchantRequestsJPanel", viewMerchantRequestsJPanel);
        CardLayout layout = (CardLayout) MerchantWorkAreajPanel.getLayout();
        layout.next(MerchantWorkAreajPanel);
    }//GEN-LAST:event_btnViewMerchantRequestActionPerformed

    // Add refreshTables method
    public void refreshTables() {
        // This method can be called from child panels to refresh any tables in the merchant homepage
        // Currently it doesn't need to do anything as there are no tables to refresh
        System.out.println("MerchantHP: refreshTables called");
    }

    // Update the existing btnTracking button to add ActionListener
    private void btnTrackingActionPerformed(java.awt.event.ActionEvent evt) {
        // Create the MerchantTrackingJPanel
        MerchantTrackingJPanel merchantTrackingJPanel = new MerchantTrackingJPanel(
            MerchantWorkAreajPanel, 
            account, 
            null, // Enterprise is null for merchant
            Business.ConfigureASystem.getLogisticsOrganization(), 
            this // Pass this as parent panel
        );
        
        MerchantWorkAreajPanel.add("MerchantTrackingJPanel", merchantTrackingJPanel);
        CardLayout layout = (CardLayout) MerchantWorkAreajPanel.getLayout();
        layout.next(MerchantWorkAreajPanel);
    }

    /**
     * Setup the theme for the merchant panel
     * Applies consistent styling to all components
     */
    private void setupTheme() {
        // Set the left panel background color
        MerchantjPanel.setBackground(new Color(12, 45, 107, 220)); // 深蓝色带透明度
        
        // Style all buttons in the panel
        styleButton(btnProductCatalog);
        styleButton(btnReports);
        styleButton(btnProfile);
        styleButton(btnViewMerchantRequest);
        styleButton(btnTracking);
        
        // Add background to the work area panel if needed
        setupWorkAreaBackground();
    }
    
    /**
     * Apply consistent style to buttons
     * @param button The button to style
     */
    private void styleButton(JButton button) {
        button.setBackground(new Color(26, 79, 156)); // 中蓝色
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        // Add a subtle border with rounded corners
        button.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(13, 60, 130), 1),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
    }
    
    /**
     * Add a background image to the work area panel
     */
    private void setupWorkAreaBackground() {
        try {
            // Create a custom JPanel with the background image
            JPanel backgroundPanel = new JPanel() {
                private Image backgroundImage;
                {
                    try {
                        backgroundImage = new ImageIcon("src/NewTechLogo.png").getImage();
                    } catch (Exception e) {
                        System.out.println("Failed to load background image: " + e.getMessage());
                    }
                }
                
                @Override
                protected void paintComponent(Graphics g) {
                    super.paintComponent(g);
                    // Draw the background image if available
                    if (backgroundImage != null) {
                        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
                    }
                }
            };
            
            // Set the layout for the background panel to be the same as MerchantWorkAreajPanel's current layout
            backgroundPanel.setLayout(new CardLayout());
            
            // Only setup background if there are no components yet
            if (MerchantWorkAreajPanel.getComponentCount() == 0) {
                MerchantWorkAreajPanel.setBackground(new Color(240, 245, 255));
            }
        } catch (Exception e) {
            System.out.println("Error setting up background: " + e.getMessage());
        }
    }
    
    /**
     * Style a text field to match the theme
     * @param textField The text field to style
     */
    private void styleTextField(JTextField textField) {
        textField.setBackground(new Color(245, 245, 250)); // 浅灰白色背景
        textField.setForeground(new Color(13, 25, 51)); // 深蓝色文字
        textField.setCaretColor(new Color(26, 79, 156)); // 中蓝色光标
        textField.setBorder(BorderFactory.createLineBorder(new Color(90, 141, 224), 1));
        textField.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MerchantWorkAreajPanel;
    private javax.swing.JPanel MerchantjPanel;
    private javax.swing.JButton btnProductCatalog;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnTracking;
    private javax.swing.JButton btnViewMerchantRequest;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
