/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.MerchantRole;


import Business.Supplier.Supplier;
import java.awt.CardLayout;

/**
 *
 * @author zhuchenyan
 */
public class MerchantHP extends javax.swing.JPanel {

    /**
     * Creates new form LogisticsCoordinatorHP
     */
    private Supplier supplier;
    
    public MerchantHP() {
        initComponents();
        // Set CardLayout for jPanel
        MerchantWorkAreajPanel.setLayout(new CardLayout());
    }
    
    public void setSupplier(Supplier supplier) {
        this.supplier = supplier;
    }
    
    public Supplier getSupplier() {
        return supplier;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        MerchantjPanel = new javax.swing.JPanel();
        btnProductCatalog = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        MerchantWorkAreajPanel = new javax.swing.JPanel();

        btnProductCatalog.setText("Manage Product Catalog");
        btnProductCatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductCatalogActionPerformed(evt);
            }
        });

        btnReports.setText("Sales Reports");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        btnProfile.setText("My Profile");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MerchantjPanelLayout = new javax.swing.GroupLayout(MerchantjPanel);
        MerchantjPanel.setLayout(MerchantjPanelLayout);
        MerchantjPanelLayout.setHorizontalGroup(
            MerchantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MerchantjPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MerchantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnProfile, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProductCatalog, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReports, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MerchantjPanelLayout.setVerticalGroup(
            MerchantjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MerchantjPanelLayout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(btnProductCatalog)
                .addGap(36, 36, 36)
                .addComponent(btnReports)
                .addGap(39, 39, 39)
                .addComponent(btnProfile)
                .addContainerGap(2441, Short.MAX_VALUE))
        );

        MerchantjPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnProductCatalog, btnProfile, btnReports});

        jSplitPane1.setLeftComponent(MerchantjPanel);

        javax.swing.GroupLayout MerchantWorkAreajPanelLayout = new javax.swing.GroupLayout(MerchantWorkAreajPanel);
        MerchantWorkAreajPanel.setLayout(MerchantWorkAreajPanelLayout);
        MerchantWorkAreajPanelLayout.setHorizontalGroup(
            MerchantWorkAreajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1397, Short.MAX_VALUE)
        );
        MerchantWorkAreajPanelLayout.setVerticalGroup(
            MerchantWorkAreajPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2888, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(MerchantWorkAreajPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProductCatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductCatalogActionPerformed
        // Check if supplier is null
        if (supplier == null) {
            // Create a default supplier if not set
            supplier = new Business.Supplier.Supplier();
            supplier.setSupplyName("Default Supplier");
        }
        
        // Create the product catalog panel
        ManageProductCatalogJPanel manageProductCatalogJPanel = new ManageProductCatalogJPanel(MerchantWorkAreajPanel, supplier);
        MerchantWorkAreajPanel.add("ManageProductCatalogJPanel", manageProductCatalogJPanel);
        CardLayout layout = (CardLayout) MerchantWorkAreajPanel.getLayout();
        layout.next(MerchantWorkAreajPanel);    
    }//GEN-LAST:event_btnProductCatalogActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        SalesReport salesReport = new SalesReport(MerchantWorkAreajPanel);
        MerchantWorkAreajPanel.add("SalesReport", salesReport);
        CardLayout layout = (CardLayout) MerchantWorkAreajPanel.getLayout();
        layout.next(MerchantWorkAreajPanel);  
    }//GEN-LAST:event_btnReportsActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        // TODO add your handling code here:
        ManageOwnProfile manageOwnProfile = new ManageOwnProfile();
        MerchantWorkAreajPanel.add("ManageOwnProfile", manageOwnProfile);
        CardLayout layout = (CardLayout) MerchantWorkAreajPanel.getLayout();
        layout.next(MerchantWorkAreajPanel);  
        
    }//GEN-LAST:event_btnProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MerchantWorkAreajPanel;
    private javax.swing.JPanel MerchantjPanel;
    private javax.swing.JButton btnProductCatalog;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnReports;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
