/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Role.Role;
import Business.Role.AdminRole;
import Business.Role.MerchantRole;
import Business.Role.CustomerServiceRepRole;
import Business.Role.LogisticsCoordinatorRole;
import Business.Role.CustomsAgentRole;
import Business.Role.WarehouseManagerRole;
import Business.Role.FintechRole;
import Business.Role.ProcurementSpecialistRole;
import Business.Role.SystemAdminRole;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.JOptionPane;

/**
 *
 * @author yushe
 */
public class AddNewUser extends javax.swing.JPanel {

    private JPanel workArea;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private AdminOrganization adminOrg;
    private EcoSystem business;
    /**
     * Creates new form AddNewUser
     */
    public AddNewUser(JPanel jp, UserAccount ua, Enterprise e, AdminOrganization ao, EcoSystem b) {
        initComponents();
        workArea = jp;
        userAccount = ua;
        enterprise = e;
        adminOrg = ao;
        business = b;
        
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        lblTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        txtEmpName = new javax.swing.JTextField();
        cmbRole = new javax.swing.JComboBox<>();
        txtUN = new javax.swing.JTextField();
        txtPW = new javax.swing.JTextField();

        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTitle.setText("Add New User");

        jLabel1.setText("Employee name:");

        jLabel2.setText("Role:");

        jLabel3.setText("Username:");

        jLabel4.setText("Password:");

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(194, 194, 194)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(btnBack)
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSave)
                            .addComponent(lblTitle))))
                .addContainerGap(277, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmbRole, txtEmpName, txtPW, txtUN});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(lblTitle)))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnSave)
                .addGap(91, 91, 91))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        workArea.remove(this);
//        AdminHP ahp = new AdminHP(workArea, userAccount, enterprise, adminOrg, business);
//        workArea.add("AdminHP", ahp);
        CardLayout l = (CardLayout) workArea.getLayout();
//        l.show(workArea, "AdminHP");
        l.previous(workArea);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // Validate input fields
        if (txtEmpName.getText().isEmpty() || txtUN.getText().isEmpty() || txtPW.getText().isEmpty() || cmbRole.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Validate password length
        if (txtPW.getText().length() < 4) {
            JOptionPane.showMessageDialog(this, "Password must be at least 4 characters long", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if username already exists
        String username = txtUN.getText();
        if (!business.checkIfUserIsUnique(username)) {
            JOptionPane.showMessageDialog(this, "Username already exists. Please choose a different username.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            // Create new employee
            Employee e = new Employee();
            e.setName(txtEmpName.getText());
            
            // Create new user account
            UserAccount newUser = new UserAccount();
            newUser.setUsername(username);
            newUser.setPassword(txtPW.getText());
            newUser.setEmployee(e);
            
            // Set role based on selection
            String selectedRole = (String) cmbRole.getSelectedItem();
            Role role = null;
            
            // Create appropriate role based on selection
            if (selectedRole.equals(new AdminRole().toString())) {
                role = new AdminRole();
            } else if (selectedRole.equals(new MerchantRole().toString())) {
                role = new MerchantRole();
            } else if (selectedRole.equals(new CustomerServiceRepRole().toString())) {
                role = new CustomerServiceRepRole();
            } else if (selectedRole.equals(new LogisticsCoordinatorRole().toString())) {
                role = new LogisticsCoordinatorRole();
            } else if (selectedRole.equals(new CustomsAgentRole().toString())) {
                role = new CustomsAgentRole();
            } else if (selectedRole.equals(new WarehouseManagerRole().toString())) {
                role = new WarehouseManagerRole();
            } else if (selectedRole.equals(new FintechRole().toString())) {
                role = new FintechRole();
            } else if (selectedRole.equals(new ProcurementSpecialistRole().toString())) {
                role = new ProcurementSpecialistRole();
            } else if (selectedRole.equals(new SystemAdminRole().toString())) {
                role = new SystemAdminRole();
            }
            
            newUser.setRole(role);
            
            // Add to both directories
            adminOrg.getUserAccountDirectory().getUserAccountList().add(newUser);
            business.getUserAccountDirectory().getUserAccountList().add(newUser);
            
            // Show success message
            JOptionPane.showMessageDialog(this, "User created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            
            // Clear fields
            txtEmpName.setText("");
            txtUN.setText("");
            txtPW.setText("");
            cmbRole.setSelectedIndex(0);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error creating user: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtEmpName;
    private javax.swing.JTextField txtPW;
    private javax.swing.JTextField txtUN;
    // End of variables declaration//GEN-END:variables

    private void populateComboBox() {
        cmbRole.removeAllItems();
        
        // Add Admin Role
        cmbRole.addItem(new AdminRole().toString());
        
        // Add Merchant Role
        cmbRole.addItem(new MerchantRole().toString());
        
        // Add Customer Service Rep Role
        cmbRole.addItem(new CustomerServiceRepRole().toString());
        
        // Add Logistics Coordinator Role
        cmbRole.addItem(new LogisticsCoordinatorRole().toString());
        
        // Add Customs Agent Role
        cmbRole.addItem(new CustomsAgentRole().toString());
        
        // Add Warehouse Manager Role
        cmbRole.addItem(new WarehouseManagerRole().toString());
        
        // Add Fintech Role
        cmbRole.addItem(new FintechRole().toString());
        
        // Add Procurement Specialist Role
        cmbRole.addItem(new ProcurementSpecialistRole().toString());
        
        // Add System Admin Role
//        cmbRole.addItem(new SystemAdminRole().toString());
    }
}
