/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.Role.SystemAdminRole;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JComboBox;
import javax.swing.JScrollPane;
import javax.swing.border.LineBorder;
import javax.swing.table.JTableHeader;
import java.awt.Component;
import java.awt.Font;
import javax.swing.JOptionPane;

/**
 *
 * @author yushe
 */
public class AdminHP extends javax.swing.JPanel {

    private JPanel workArea;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private AdminOrganization adminOrg;
    private EcoSystem business;
    
    
  
    public AdminHP() {

//        System.out.println("⚠️ Warning: Default constructor used — make sure this is intentional!");
//        initComponents();
//        this.setPreferredSize(new java.awt.Dimension(1450, 800));
//        populateTable();
        
//         throw new RuntimeException("🚨 Default constructor of AdminHP used! Stack trace below:");
    }
    
    public AdminHP(JPanel jp, UserAccount ua, Enterprise e, AdminOrganization o, EcoSystem b) {
        this.setPreferredSize(new java.awt.Dimension(1450, 800));
        this.workArea = jp;
        this.userAccount = ua;
        this.enterprise = e;
        adminOrg = o;
        business = b;
        
//         Transfer user accounts from system to AdminOrganization
        if (adminOrg != null && business != null) {
            System.out.println("Transferring user accounts from system to AdminOrganization...");
            for (UserAccount systemUA : business.getUserAccountDirectory().getUserAccountList()) {
                adminOrg.getUserAccountDirectory().getUserAccountList().add(systemUA);
            }
            System.out.println("Transferred " + adminOrg.getUserAccountDirectory().getUserAccountList().size() + " user accounts");
        }
        
        System.out.println("Received JPanel: " + (jp != null ? "Not null ✅" : "NULL ❌"));
        System.out.println("JPanel class: " + (jp != null ? jp.getClass().getName() : "null"));
        System.out.println("AdminOrg: " + (adminOrg != null ? "Not null ✅" : "NULL ❌"));
        System.out.println("UserAccountDirectory: " + (adminOrg != null && adminOrg.getUserAccountDirectory() != null ? "Not null ✅" : "NULL ❌"));
        System.out.println("Number of user accounts: " + (adminOrg != null && adminOrg.getUserAccountDirectory() != null ? adminOrg.getUserAccountDirectory().getUserAccountList().size() : "N/A"));
        
        initComponents();
        populateTable();
        setupTableSelectionListener();
        setModifyPanelEnabled(false); // Disable modify panel initially
        
        // Apply unified UI theme
        setupTheme();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeMsg = new javax.swing.JLabel();
        btnMngOwnProfile = new javax.swing.JButton();
        viewUsersScrollPane = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnAddUser = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        maintenanceCorner = new javax.swing.JPanel();
        lblMaintenance = new javax.swing.JLabel();
        lblModifyMsg = new javax.swing.JLabel();
        lblUN = new javax.swing.JLabel();
        lblPW = new javax.swing.JLabel();
        txtModUN = new javax.swing.JTextField();
        txtModPW = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        actionCorner = new javax.swing.JPanel();
        lblAction = new javax.swing.JLabel();
        viewSusScrollPane = new javax.swing.JScrollPane();
        tblSus = new javax.swing.JTable();
        btnAcc = new javax.swing.JButton();
        btnDeny = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();

        WelcomeMsg.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WelcomeMsg.setText("Welcome Admin!");

        btnMngOwnProfile.setText("Manage My Own Profile");
        btnMngOwnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngOwnProfileActionPerformed(evt);
            }
        });

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Username", "ID", "Employee Name", "Role", "Password"
            }
        ));
        viewUsersScrollPane.setViewportView(tblUsers);

        btnAddUser.setText("Add User");
        btnAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddUserActionPerformed(evt);
            }
        });

        btnModify.setText("Modify User");
        btnModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete User");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSearch.setText("Search User");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("User List");

        maintenanceCorner.setBackground(new java.awt.Color(255, 255, 255));

        lblMaintenance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaintenance.setText("Modify User Work Space");

        lblModifyMsg.setText(" ");

        lblUN.setText("Username:");

        lblPW.setText("Password:");

        btnUpdate.setText("Update");

        javax.swing.GroupLayout maintenanceCornerLayout = new javax.swing.GroupLayout(maintenanceCorner);
        maintenanceCorner.setLayout(maintenanceCornerLayout);
        maintenanceCornerLayout.setHorizontalGroup(
            maintenanceCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceCornerLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(maintenanceCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(maintenanceCornerLayout.createSequentialGroup()
                        .addComponent(lblUN)
                        .addGap(18, 18, 18)
                        .addComponent(txtModUN, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(maintenanceCornerLayout.createSequentialGroup()
                        .addComponent(lblPW)
                        .addGap(18, 18, 18)
                        .addGroup(maintenanceCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUpdate)
                            .addComponent(txtModPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maintenanceCornerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblMaintenance)
                .addGap(118, 118, 118))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, maintenanceCornerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblModifyMsg)
                .addGap(197, 197, 197))
        );

        maintenanceCornerLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtModPW, txtModUN});

        maintenanceCornerLayout.setVerticalGroup(
            maintenanceCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceCornerLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblMaintenance)
                .addGap(18, 18, 18)
                .addComponent(lblModifyMsg)
                .addGap(31, 31, 31)
                .addGroup(maintenanceCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUN)
                    .addComponent(txtModUN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(maintenanceCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPW)
                    .addComponent(txtModPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(btnUpdate)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        actionCorner.setBackground(new java.awt.Color(255, 255, 255));

        lblAction.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAction.setText("Suspend Suspicious Activities");

        tblSus.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Payment ID", "Shipment Info", "Amount"
            }
        ));
        viewSusScrollPane.setViewportView(tblSus);

        btnAcc.setText("Accept");

        btnDeny.setText("Deny");

        javax.swing.GroupLayout actionCornerLayout = new javax.swing.GroupLayout(actionCorner);
        actionCorner.setLayout(actionCornerLayout);
        actionCornerLayout.setHorizontalGroup(
            actionCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionCornerLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(lblAction)
                .addGap(126, 126, 126))
            .addGroup(actionCornerLayout.createSequentialGroup()
                .addGroup(actionCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(actionCornerLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(viewSusScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(actionCornerLayout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(btnAcc)
                        .addGap(60, 60, 60)
                        .addComponent(btnDeny)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        actionCornerLayout.setVerticalGroup(
            actionCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionCornerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAction)
                .addGap(39, 39, 39)
                .addComponent(viewSusScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(actionCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcc)
                    .addComponent(btnDeny))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        btnRefresh.setText("Refresh List");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddUser)
                .addGap(79, 79, 79)
                .addComponent(btnModify)
                .addGap(66, 66, 66)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(actionCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(maintenanceCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewUsersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(47, 47, 47)
                                .addComponent(btnRefresh))
                            .addComponent(WelcomeMsg))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(btnMngOwnProfile))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearch)))))
                .addContainerGap(417, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(maintenanceCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMngOwnProfile)
                            .addComponent(WelcomeMsg))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSearch)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(btnRefresh))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewUsersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddUser)
                            .addComponent(btnModify)
                            .addComponent(btnDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(actionCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngOwnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngOwnProfileActionPerformed
        // TODO add your handling code here:
        AdminManageOwnProfile amop = new AdminManageOwnProfile(workArea, userAccount);
        workArea.add("AdminManageOwn", amop);
        CardLayout l = (CardLayout) workArea.getLayout();
        l.show(workArea, "AdminManageOwn");
        
    }//GEN-LAST:event_btnMngOwnProfileActionPerformed

    private void btnAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddUserActionPerformed
        // TODO add your handling code here:
        AddNewUser anu = new AddNewUser(workArea, userAccount, enterprise, adminOrg, business);
        workArea.add("AddNewUser", anu);
        CardLayout l = (CardLayout) workArea.getLayout();
        l.show(workArea, "AddNewUser");
    }//GEN-LAST:event_btnAddUserActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        updateUAD();
        populateTable();
        jTextField1.setText(""); // Clear search field
        JOptionPane.showMessageDialog(this, "List refreshed successfully!", "Refresh", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // Get the selected row
        int selectedRow = tblUsers.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a user to delete", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Get the user account from the selected row
        UserAccount userToDelete = (UserAccount) tblUsers.getValueAt(selectedRow, 0);
        
        // Check if user is System Admin
        if (userToDelete.getRole() instanceof SystemAdminRole) {
            JOptionPane.showMessageDialog(this, "You cannot delete System Admin", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete user: " + userToDelete.getUsername() + "?",
            "Confirm Deletion",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.WARNING_MESSAGE);
            
        if (confirm == JOptionPane.YES_OPTION) {
            // Remove from both directories
            adminOrg.getUserAccountDirectory().getUserAccountList().remove(userToDelete);
            business.getUserAccountDirectory().getUserAccountList().remove(userToDelete);
            
            // Update the table
            populateTable();
            
            JOptionPane.showMessageDialog(this, "User deleted successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyActionPerformed
        // Get the selected row
        int selectedRow = tblUsers.getSelectedRow();
        
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a user to modify", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Get the user account from the selected row
        UserAccount userToModify = (UserAccount) tblUsers.getValueAt(selectedRow, 0);
        
        // Check if user is System Admin
        if (userToModify.getRole() instanceof SystemAdminRole) {
            JOptionPane.showMessageDialog(this, "You cannot modify System Admin from here", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Enable modify panel and display current info
        setModifyPanelEnabled(true);
        txtModUN.setText(userToModify.getUsername());
        txtModPW.setText(userToModify.getPassword());
        lblModifyMsg.setText("Modifying user: " + userToModify.getUsername());
        
        // Add action listener to update button if not already added
        if (btnUpdate.getActionListeners().length == 0) {
            btnUpdate.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    updateUserInfo(userToModify);
                    setModifyPanelEnabled(false); // Disable panel after update
                }
            });
        }
    }//GEN-LAST:event_btnModifyActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String searchText = jTextField1.getText().trim();
        
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a username to search", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        DefaultTableModel m = (DefaultTableModel) tblUsers.getModel();
        m.setRowCount(0); // Clear the table
        
        boolean found = false;
        for (UserAccount ua : adminOrg.getUserAccountDirectory().getUserAccountList()) {
            if (ua.getUsername().toLowerCase().contains(searchText.toLowerCase())) {
                Object[] row = new Object[5];
                row[0] = ua;
                row[1] = ua.getEmployee().getId();
                row[2] = ua.getEmployee().toString();
                row[3] = ua.getRole();
                row[4] = ua.getPassword();
                m.addRow(row);
                found = true;
            }
        }
        
        if (!found) {
            JOptionPane.showMessageDialog(this, "No users found matching: " + searchText, "Search Results", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Search completed. Click Refresh to see all users.", "Search Results", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSearchActionPerformed
    
    private void updateUserInfo(UserAccount userToModify) {
        String newUsername = txtModUN.getText().trim();
        String newPassword = txtModPW.getText().trim();
        
        // Validate input
        if (newUsername.isEmpty() || newPassword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Username and password cannot be empty", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if password meets minimum length
        if (newPassword.length() < 4) {
            JOptionPane.showMessageDialog(this, "Password must be at least 4 characters long", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if username is being changed to an existing one
        if (!newUsername.equals(userToModify.getUsername()) && !business.checkIfUserIsUnique(newUsername)) {
            JOptionPane.showMessageDialog(this, "Username already exists. Please choose a different username.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Check if any changes were made
        if (newUsername.equals(userToModify.getUsername()) && newPassword.equals(userToModify.getPassword())) {
            JOptionPane.showMessageDialog(this, "No changes were made", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        
        try {
            // Update user info
            userToModify.setUsername(newUsername);
            userToModify.setPassword(newPassword);
            
            // Update the table
            populateTable();
            
            // Clear modify panel
            txtModUN.setText("");
            txtModPW.setText("");
            lblModifyMsg.setText(" ");
            
            JOptionPane.showMessageDialog(this, "User information updated successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error updating user: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WelcomeMsg;
    private javax.swing.JPanel actionCorner;
    private javax.swing.JButton btnAcc;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeny;
    private javax.swing.JButton btnMngOwnProfile;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAction;
    private javax.swing.JLabel lblMaintenance;
    private javax.swing.JLabel lblModifyMsg;
    private javax.swing.JLabel lblPW;
    private javax.swing.JLabel lblUN;
    private javax.swing.JPanel maintenanceCorner;
    private javax.swing.JTable tblSus;
    private javax.swing.JTable tblUsers;
    private javax.swing.JTextField txtModPW;
    private javax.swing.JTextField txtModUN;
    private javax.swing.JScrollPane viewSusScrollPane;
    private javax.swing.JScrollPane viewUsersScrollPane;
    // End of variables declaration//GEN-END:variables
    
    
    // operations
    private void populateTable() {
        DefaultTableModel m = (DefaultTableModel) tblUsers.getModel();
        m.setRowCount(0);
        
        // Debug logging
        System.out.println("Accessing UserAccountDirectory from AdminOrganization...");
        System.out.println("AdminOrg: " + (adminOrg != null ? "Not null ✅" : "NULL ❌"));
        System.out.println("UserAccountDirectory: " + (adminOrg != null && adminOrg.getUserAccountDirectory() != null ? "Not null ✅" : "NULL ❌"));
        
        if (adminOrg != null && adminOrg.getUserAccountDirectory() != null) {
            System.out.println("Number of user accounts: " + adminOrg.getUserAccountDirectory().getUserAccountList().size());
            System.out.println("User accounts: " + adminOrg.getUserAccountDirectory().getUserAccountList());
        }
        
        for (UserAccount ua : adminOrg.getUserAccountDirectory().getUserAccountList()) {
            System.out.println("Processing user account: " + ua.toString());
            Object[] row = new Object[5];
            row[0] = ua;
            row[1] = ua.getEmployee().getId();
            row[2] = ua.getEmployee().toString();
            row[3] = ua.getRole();
            row[4] = ua.getPassword();
            m.addRow(row);
        }
    }
    
    /**
     * Style the modify user workspace
     */
    private void styleModifyWorkspace() {
        // Style the maintenance corner panel
        maintenanceCorner.setBackground(new Color(245, 245, 250));
        maintenanceCorner.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(200, 200, 220), 1),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));
        
        // Style the title label
        lblMaintenance.setForeground(new Color(26, 79, 156));
        lblMaintenance.setFont(new Font("Helvetica Neue", Font.BOLD, 16));
        
        // Style the message label
        lblModifyMsg.setForeground(new Color(100, 100, 100));
        lblModifyMsg.setFont(new Font("Helvetica Neue", Font.ITALIC, 12));
        
        // Style the input labels
        lblUN.setForeground(new Color(26, 79, 156));
        lblPW.setForeground(new Color(26, 79, 156));
        lblUN.setFont(new Font("Helvetica Neue", Font.BOLD, 12));
        lblPW.setFont(new Font("Helvetica Neue", Font.BOLD, 12));
        
        // Style the text fields
        styleTextField(txtModUN);
        styleTextField(txtModPW);
        
        // Style the update button
        styleButton(btnUpdate);
        btnUpdate.setBackground(new Color(52, 152, 219)); // Different color for update button
        btnUpdate.setForeground(Color.WHITE);
        
        // Add hover effects
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdate.setBackground(new Color(41, 128, 185));
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnUpdate.setBackground(new Color(52, 152, 219));
            }
        });
    }
    
    // Update the setupTheme method to include modify workspace styling
    private void setupTheme() {
        // Set panel background color
        this.setBackground(new Color(240, 245, 255));
        
        // Style all buttons
        styleAllButtons();
        
        // Style all labels
        styleAllLabels();
        
        // Style the modify workspace
        styleModifyWorkspace();
    }
    
    /**
     * Apply consistent styling to all buttons
     */
    private void styleAllButtons() {
        Component[] components = this.getComponents();
        for (Component component : components) {
            if (component instanceof JButton) {
                styleButton((JButton) component);
            }
            if (component instanceof JPanel) {
                Component[] panelComponents = ((JPanel) component).getComponents();
                for (Component panelComponent : panelComponents) {
                    if (panelComponent instanceof JButton) {
                        styleButton((JButton) panelComponent);
                    }
                }
            }
        }
    }
    
    /**
     * Apply consistent styling to a button
     * @param button Button to style
     */
    private void styleButton(JButton button) {
        button.setBackground(new Color(26, 79, 156)); // Medium blue
        button.setForeground(Color.WHITE);
        button.setFocusPainted(false);
        button.setBorderPainted(false);
        // Add a subtle border with rounded corners
        button.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(13, 60, 130), 1),
            BorderFactory.createEmptyBorder(5, 10, 5, 10)
        ));
        button.setFont(new Font("Helvetica Neue", Font.BOLD, 14));
    }
    
    /**
     * Apply consistent styling to all labels
     */
    private void styleAllLabels() {
        Component[] components = this.getComponents();
        for (Component component : components) {
            if (component instanceof JLabel) {
                if (((JLabel) component).getFont().getSize() > 15) {
                    styleTitleLabel((JLabel) component);
                } else {
                    styleLabel((JLabel) component);
                }
            }
            if (component instanceof JPanel) {
                Component[] panelComponents = ((JPanel) component).getComponents();
                for (Component panelComponent : panelComponents) {
                    if (panelComponent instanceof JLabel) {
                        if (((JLabel) panelComponent).getFont().getSize() > 15) {
                            styleTitleLabel((JLabel) panelComponent);
                        } else {
                            styleLabel((JLabel) panelComponent);
                        }
                    }
                }
            }
        }
    }
    
    /**
     * Apply title label styling
     * @param label Label to style
     */
    private void styleTitleLabel(JLabel label) {
        label.setForeground(new Color(26, 79, 156));
        label.setFont(new Font("Helvetica Neue", Font.BOLD, 20));
    }
    
    /**
     * Apply regular label styling
     * @param label Label to style
     */
    private void styleLabel(JLabel label) {
        label.setForeground(new Color(26, 79, 156));
        label.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
    }
    
    /**
     * Apply consistent styling to a text field
     * @param textField TextField to style
     */
    private void styleTextField(JTextField textField) {
        textField.setBackground(new Color(245, 245, 250)); // Light gray-white background
        textField.setForeground(new Color(13, 25, 51)); // Dark blue text
        textField.setCaretColor(new Color(26, 79, 156)); // Medium blue cursor
        textField.setBorder(BorderFactory.createLineBorder(new Color(90, 141, 224), 1));
        textField.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
    }
    
    /**
     * Style a combo box to match the theme
     * @param comboBox ComboBox to style
     */
    private void styleComboBox(JComboBox comboBox) {
        comboBox.setBackground(new Color(245, 245, 250)); // Light gray-white background
        comboBox.setForeground(new Color(13, 25, 51)); // Dark blue text
        comboBox.setBorder(BorderFactory.createLineBorder(new Color(90, 141, 224), 1));
        comboBox.setFont(new Font("Helvetica Neue", Font.PLAIN, 14));
        
        // Style the UI if possible
        try {
            comboBox.setUI(new javax.swing.plaf.basic.BasicComboBoxUI() {
                @Override
                protected JButton createArrowButton() {
                    JButton button = super.createArrowButton();
                    button.setBackground(new Color(26, 79, 156));
                    button.setBorder(BorderFactory.createLineBorder(new Color(90, 141, 224)));
                    return button;
                }
            });
        } catch (Exception e) {
            System.out.println("Could not fully style combo box: " + e.getMessage());
        }
    }
    
    /**
     * Style table with consistent theme
     * @param table Table to style
     * @param scrollPaneName Name of the scrollpane containing the table
     */
    private void styleTable(JTable table, String scrollPaneName) {
        // Style table header
        JTableHeader header = table.getTableHeader();
        header.setBackground(new Color(26, 79, 156));
        header.setForeground(Color.WHITE);
        header.setFont(new Font("Helvetica Neue", Font.BOLD, 14));
        header.setBorder(new LineBorder(new Color(13, 60, 130)));
        
        // Style table - using darker colors for better visibility
        table.setBackground(new Color(240, 240, 250)); // Slightly darker background
        table.setForeground(new Color(0, 0, 0)); // Black text for maximum contrast
        table.setGridColor(new Color(180, 195, 235)); // Darker grid lines
        table.setSelectionBackground(new Color(90, 141, 224));
        table.setSelectionForeground(Color.WHITE);
        table.setFont(new Font("Helvetica Neue", Font.BOLD, 14)); // Bold font for better visibility
        table.setRowHeight(30); // Slightly increase row height for better readability
        
        // Set alternating row colors with more contrast
        table.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                if (!isSelected) {
                    c.setBackground(row % 2 == 0 ? new Color(240, 240, 250) : new Color(220, 220, 235));
                    c.setForeground(new Color(0, 0, 0)); // Ensure text is always black for maximum contrast
                }
                return c;
            }
        });
        
        // Find and style the scroll pane if it exists
        try {
            Component[] components = this.getComponents();
            for (Component component : components) {
                if (component instanceof JScrollPane && component.getName() != null && 
                    component.getName().equals(scrollPaneName)) {
                    ((JScrollPane) component).setBorder(new LineBorder(new Color(26, 79, 156)));
                    break;
                }
            }
        } catch (Exception e) {
            System.out.println("Could not find scroll pane for table: " + e.getMessage());
        }
    }
    
    private void updateUAD() {
        adminOrg.setUad(business.getUserAccountDirectory());
    }

    // Add this method to control modify panel state
    private void setModifyPanelEnabled(boolean enabled) {
        txtModUN.setEnabled(enabled);
        txtModPW.setEnabled(enabled);
        btnUpdate.setEnabled(enabled);
        
        // Visual feedback for enabled/disabled state
        if (enabled) {
            maintenanceCorner.setBackground(new Color(245, 245, 250));
            lblModifyMsg.setForeground(new Color(26, 79, 156));
        } else {
            maintenanceCorner.setBackground(new Color(235, 235, 240));
            lblModifyMsg.setForeground(new Color(150, 150, 150));
        }
        
        // Clear fields when disabled
        if (!enabled) {
            txtModUN.setText("");
            txtModPW.setText("");
            lblModifyMsg.setText(" ");
        }
    }

    // Modify the table selection listener
    private void setupTableSelectionListener() {
        tblUsers.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                int selectedRow = tblUsers.getSelectedRow();
                if (selectedRow >= 0) {
                    UserAccount selectedUser = (UserAccount) tblUsers.getValueAt(selectedRow, 0);
                    boolean isSystemAdmin = selectedUser.getRole() instanceof SystemAdminRole;
                    
                    // Disable/enable buttons based on role
                    btnModify.setEnabled(!isSystemAdmin);
                    btnDelete.setEnabled(!isSystemAdmin);
                    
                    // Visual feedback for disabled buttons
                    if (isSystemAdmin) {
                        btnModify.setToolTipText("Cannot modify System Admin");
                        btnDelete.setToolTipText("Cannot delete System Admin");
                    } else {
                        btnModify.setToolTipText(null);
                        btnDelete.setToolTipText(null);
                    }
                    
                    // Disable modify panel by default
                    setModifyPanelEnabled(false);
                } else {
                    // No row selected, disable everything
                    btnModify.setEnabled(false);
                    btnDelete.setEnabled(false);
                    setModifyPanelEnabled(false);
                }
            }
        });
    }
}
