/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.AdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.AdminOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author yushe
 */
public class AdminHP extends javax.swing.JPanel {

    private JPanel workArea;
    private UserAccount userAccount;
    private Enterprise enterprise;
    private AdminOrganization adminOrg;
    
    
  
    public AdminHP() {
        System.out.println("⚠️ Warning: Default constructor used — make sure this is intentional!");
        initComponents();
        this.setPreferredSize(new java.awt.Dimension(1450, 800));
    }
    
    public AdminHP(JPanel jp, UserAccount ua, Enterprise e, AdminOrganization ao) {
        System.out.println("⚠️ Warning: Default constructor used — make sure this is intentional!");
        this.setPreferredSize(new java.awt.Dimension(1450, 800));
        this.workArea = jp;
        this.userAccount = ua;
        this.enterprise = e;
        adminOrg = ao;
        System.out.println("Received JPanel: " + (jp != null ? "Not null ✅" : "NULL ❌"));
        System.out.println("JPanel class: " + (jp != null ? jp.getClass().getName() : "null"));
        initComponents();
//        System.out.println(workArea.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WelcomeMsg = new javax.swing.JLabel();
        btnMngOwnProfile = new javax.swing.JButton();
        viewUsersScrollPane = new javax.swing.JScrollPane();
        tblUsers = new javax.swing.JTable();
        btnAddUser = new javax.swing.JButton();
        btnModify = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        maintenanceCorner = new javax.swing.JPanel();
        lblMaintenance = new javax.swing.JLabel();
        actionCorner = new javax.swing.JPanel();
        lblAction = new javax.swing.JLabel();

        WelcomeMsg.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        WelcomeMsg.setText("Welcome Admin!");

        btnMngOwnProfile.setText("Manage My Own Profile");
        btnMngOwnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngOwnProfileActionPerformed(evt);
            }
        });

        tblUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Employee Name", "ID", "Role", "Username", "Password"
            }
        ));
        viewUsersScrollPane.setViewportView(tblUsers);

        btnAddUser.setText("Add User");

        btnModify.setText("Modify User");

        btnDelete.setText("Delete User");

        btnSearch.setText("Search User");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("User List");

        maintenanceCorner.setBackground(new java.awt.Color(255, 255, 255));

        lblMaintenance.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMaintenance.setText("Maintenance");

        javax.swing.GroupLayout maintenanceCornerLayout = new javax.swing.GroupLayout(maintenanceCorner);
        maintenanceCorner.setLayout(maintenanceCornerLayout);
        maintenanceCornerLayout.setHorizontalGroup(
            maintenanceCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceCornerLayout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(lblMaintenance)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        maintenanceCornerLayout.setVerticalGroup(
            maintenanceCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(maintenanceCornerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblMaintenance)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        actionCorner.setBackground(new java.awt.Color(255, 255, 255));

        lblAction.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAction.setText("Suspend Suspicious Activities");

        javax.swing.GroupLayout actionCornerLayout = new javax.swing.GroupLayout(actionCorner);
        actionCorner.setLayout(actionCornerLayout);
        actionCornerLayout.setHorizontalGroup(
            actionCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, actionCornerLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(lblAction)
                .addGap(126, 126, 126))
        );
        actionCornerLayout.setVerticalGroup(
            actionCornerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionCornerLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblAction)
                .addContainerGap(282, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddUser)
                .addGap(79, 79, 79)
                .addComponent(btnModify)
                .addGap(66, 66, 66)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(maintenanceCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(actionCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(viewUsersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(WelcomeMsg)
                        .addGap(139, 139, 139)
                        .addComponent(btnMngOwnProfile)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMngOwnProfile)
                    .addComponent(WelcomeMsg))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSearch)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewUsersScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddUser)
                    .addComponent(btnModify)
                    .addComponent(btnDelete))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maintenanceCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionCorner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngOwnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngOwnProfileActionPerformed
        // TODO add your handling code here:
        AdminManageOwnProfile amop = new AdminManageOwnProfile(workArea, userAccount);
        workArea.add("AdminManageOwn", amop);
        CardLayout l = (CardLayout) workArea.getLayout();
        l.show(workArea, "AdminManageOwn");
        
    }//GEN-LAST:event_btnMngOwnProfileActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WelcomeMsg;
    private javax.swing.JPanel actionCorner;
    private javax.swing.JButton btnAddUser;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnMngOwnProfile;
    private javax.swing.JButton btnModify;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblAction;
    private javax.swing.JLabel lblMaintenance;
    private javax.swing.JPanel maintenanceCorner;
    private javax.swing.JTable tblUsers;
    private javax.swing.JScrollPane viewUsersScrollPane;
    // End of variables declaration//GEN-END:variables
}
